services:
  api:
    build:
      context: .
      args:
        PORT: ${PORT}
        PUID: ${PUID}
        PGID: ${PGID}
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: unless-stopped
    container_name: api_collection
    volumes:
      - ./data:/app/data